openapi: 3.0.3
info:
  title: Health Check API
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  /healthCheck:
    get:
      summary: Get health check status
      operationId: HealthCheck
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    HealthCheckResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string